version: '3.0'
services:
    nginx:
        #restart: always
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - /home/semenov/UpdateManager/nginx.conf:/etc/nginx/conf.d/default.conf
            - /www
        depends_on:
            - mapteka-get
        command: /bin/ash -c "chmod 777 /www && nginx -g 'daemon off;'"
    
    update-manager:
        #restart: always
        build:
            context: .
        ports:
            - 8080:80
        depends_on:
            - postgres
        environment:
            - STATIC_BASE_URI=http://nginx/
            - DB_CONNECTION_STR=server=postgres;port=5432;database=updater
            - LOG_LEVEL=Debug
            - POSTGRES_USER=postgres

    postgres:
        # restart: always
        image: postgres:alpine
        ports:
            - 5432:5432


